### ISSUE TITLE
An error occurred during the fetch of repository 'org_theopenroadproject':

### ISSUE THREAD

**Issue by LivanKov** [google/xls#1705]
System: Ubuntu 22.04.5 LTS on WSL 2.3.24.0 (tried Ubuntu 20.04.6 as well)
Bazel: version 7.4.0 (tried version 7.0.0 as well)

When attempting to build from source I always get the following error a couple of minutes in: 
```
An error occurred during the fetch of repository 'org_theopenroadproject':
   Traceback (most recent call last):
        File "/home/ivan/.cache/bazel/_bazel_ivan/4b7fa2f66bee2e76a1c3cd0648b6021f/external/bazel_tools/tools/build_defs/repo/git.bzl", line 180, column 35, in _git_repository_implementation
                update = _clone_or_update_repo(ctx)
        File "/home/ivan/.cache/bazel/_bazel_ivan/4b7fa2f66bee2e76a1c3cd0648b6021f/external/bazel_tools/tools/build_defs/repo/git.bzl", line 43, column 20, in _clone_or_update_repo
                git_ = git_repo(ctx, directory)
        File "/home/ivan/.cache/bazel/_bazel_ivan/4b7fa2f66bee2e76a1c3cd0648b6021f/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 98, column 12, in git_repo
                _update(ctx, git_repo)
        File "/home/ivan/.cache/bazel/_bazel_ivan/4b7fa2f66bee2e76a1c3cd0648b6021f/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 116, column 10, in _update
                fetch(ctx, git_repo)
        File "/home/ivan/.cache/bazel/_bazel_ivan/4b7fa2f66bee2e76a1c3cd0648b6021f/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 150, column 13, in fetch
                _git(
        File "/home/ivan/.cache/bazel/_bazel_ivan/4b7fa2f66bee2e76a1c3cd0648b6021f/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 186, column 15, in _git
                _error(ctx.name, ["git"] + start + list(args), st.stderr)
        File "/home/ivan/.cache/bazel/_bazel_ivan/4b7fa2f66bee2e76a1c3cd0648b6021f/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 210, column 9, in _error
                fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @org_theopenroadproject:
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 6718 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
ERROR: no such package '@@org_theopenroadproject//': error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @org_theopenroadproject:
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 6718 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
ERROR: /home/ivan/xls/xls/modules/rle/BUILD:318:16: //xls/modules/rle:rle_dec_place_and_route_asap7 depends on @@org_theopenroadproject//:openroad in repository @@org_theopenroadproject which failed to fetch. no such package '@@org_theopenroadproject//': error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @org_theopenroadproject:
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 6718 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
ERROR: Analysis of target '//xls/modules/rle:rle_build_test' failed; build aborted: Analysis failed
INFO: Elapsed time: 216.555s, Critical Path: 0.22s
INFO: 15 processes: 7 internal, 8 linux-sandbox.
ERROR: Build did NOT complete successfully
//xls/build_rules/tests:generated_frozen_x_sha256sum_test                PASSED in 0.0s
//xls/build_rules/tests:generated_x_sha256sum_test                       PASSED in 0.0s

Executed 2 out of 2 tests: 2 tests pass.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
All tests passed but there were other errors during the build.
``` 

I'm fairly certain that I've followed all of the steps in the setup.

Any help for what might be potentially causing this issue, would be greatly appreciated!

Kind regards

**Comment by ericastor** [comment]
The base error seems to be this:

```
Error in fail: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @org_theopenroadproject:
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 6718 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

which suggests that the issue is that you're having connection issues to GitHub while Bazel tries to fetch the OpenROAD dependency for XLS. Apologies, but I don't think we're in a position to help debug network problems.
